name: Test Scripts

on:
  push:
    branches:
      - test-script

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - name: First
            path: "./apps/first"
          - name: Second
            path: "./apps/second"

    name: Test ${{ matrix.app.name }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: CI
        run: deno install

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Build Test
        run: deno task --cwd ${{ matrix.app.path }} build
